"""empty message

Revision ID: 059c850bcfdf
Revises: 2079b60dfd5c
Create Date: 2025-08-18 23:03:43.088649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059c850bcfdf'
down_revision = '2079b60dfd5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
