"""empty message

Revision ID: 4bb185ae360a
Revises: 0763d677d453
Create Date: 2025-08-12 00:31:18.384355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb185ae360a'
down_revision = '0763d677d453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('fname', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('lname', sa.String(length=120), nullable=False))
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('lname')
        batch_op.drop_column('fname')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
